# To use it, install Builder (https://github.com/ImSumire/Builder)

# Build variables
target = "dist/main"
src = "main.c"

test_target = "dist/test"
test_src = "test/test.c"

optimization = "g"
warnings = "-Wall -Wextra"

[tree]
commands = [
    "command -v lsd >/dev/null 2>&1 && lsd --tree . || ls -R ."
]

[debug]
commands = [
    "mkdir -p dist",

    "printf '\\e[34mi \\e[30mCompiling (debug)\\e[0m\n'",
    "gcc -O$optimization -g -o $target $src $warnings",
    "printf '\\e[32m✔ \\e[30mCompilation done!\\e[0m\n\n'",

    "valgrind --log-file='log/.valgrind' --leak-check=full --show-leak-kinds=all $target"
]

[test]
commands = [
    "mkdir -p dist",
    
    "printf '\\e[34mi \\e[30mCompiling (test)\\e[0m\n'",
    "gcc -Og -g -o $test_target $test_src $warnings",
    "printf '\\e[32m✔ \\e[30mCompilation done!\\e[0m\n\n'",

    "valgrind --log-file='log/.valgrind' --leak-check=full --show-leak-kinds=all $test_target"
]

[build]
commands = [
    "mkdir -p dist",
    
    "printf '\\e[34mi \\e[30mCompiling\\e[0m\n'",
    "gcc -O$optimization -o $target $src $warnings",
    "printf '\\e[32m✔ \\e[30mCompilation done!\\e[0m\n\n'"
]

[prod]
commands = [
    "mkdir -p dist",
    
    "printf '\\e[34mi \\e[30mCompiling (production)\\e[0m\n'",
    "gcc -Ofast -o $target $src",
    "printf '\\e[32m✔ \\e[30mCompilation done!\\e[0m\n\n'"
]

[run]
commands = [
    "$target"
]
